"""Rule-based multi-label categorization for Korean Steam reviews."""

from __future__ import annotations

from analysis.rules import normalize_text

CATEGORY_PATTERNS: dict[str, tuple[str, ...]] = {
    "bugs": (
        "버그",
        "오류",
        "에러",
        "충돌",
        "크래시",
        "멈춤",
        "깨짐",
        "깨진",
        "이상함",
        "정지",
        "불가",
        "막혀",
        "로그인",
        "접속불가",
        "진행불가",
        "계정",
        "검사중",
    ),
    "performance": (
        "최적화",
        "최적화문제",
        "프레임",
        "프레임드랍",
        "렉",
        "버벅",
        "로딩",
        "발열",
        "무거움",
        "실행안",
        "안됨",
        "꺼짐",
        "튕김",
        "그래픽카드",
        "그리픽카드",
    ),
    "balance": (
        "밸런스",
        "사기",
        "너프",
        "버프",
        "op",
        "밸패",
        "판자",
        "발전기",
    ),
    "story": (
        "스토리",
        "서사",
        "시나리오",
        "연출",
        "캐릭터",
        "몰입",
        "여운",
        "감동",
    ),
    "graphics": (
        "그래픽",
        "비주얼",
        "아트",
        "모델링",
        "연출",
        "분위기",
    ),
    "gameplay": (
        "전투",
        "타격감",
        "손맛",
        "액션",
        "빌드",
        "무기",
        "스킬",
        "패링",
        "회피",
        "탐험",
        "오픈월드",
        "던전",
    ),
    "monetization": (
        "과금",
        "가격",
        "bm",
        "dlc",
        "디엘씨",
        "패스",
        "확장팩",
        "현질",
        "키트",
    ),
    "multiplayer": (
        "매칭",
        "서버",
        "멀티",
        "파티",
        "듀오",
        "솔로",
        "협동",
        "핑",
        "팀원",
        "픽창",
        "역할군",
        "핵",
        "매크로",
        "mmr",
        "해킹",
        "밴",
        "약탈",
        "털려",
        "살인마",
        "생존자",
        "다인큐",
    ),
    "localization": (
        "번역",
        "오역",
        "현지화",
        "자막",
        "한국어",
    ),
    "difficulty": (
        "난이도",
        "온보딩",
        "튜토리얼",
        "불친절",
        "초반",
        "초보",
        "뉴비",
        "입문",
        "어려워",
        "어렵",
        "고인물",
    ),
    "controls": (
        "조작",
        "조작감",
        "키맵",
        "ui",
        "입력",
        "반응속도",
        "답답",
        "불편",
        "패드",
        "휠",
        "멀미",
    ),
    "content_depth": (
        "콘텐츠",
        "볼륨",
        "할게없",
        "할것도없",
        "할거없",
        "할요소",
        "지루",
        "심심",
        "생동감",
        "인터랙션",
        "목적성",
        "깊이",
        "유동성",
        "반복적",
        "노가다",
        "파밍",
        "숙제",
        "폐지줍기",
        "킬링타임",
        "시간순삭",
    ),
    "building_ux": (
        "건축",
        "건설",
        "부지",
        "데크",
        "중정",
        "경사진바닥",
        "경사바닥",
        "비스듬",
        "집짓",
        "건축모드",
        "배치",
    ),
    "save_progression": (
        "저장",
        "세이브",
        "날아감",
        "날려",
        "유실",
        "이어하기",
    ),
    "mod_support": (
        "모드",
        "공식지원",
        "호환",
        "활성화",
        "연결",
        "cc템",
        "크리에이션클럽",
    ),
    "customization": (
        "커스터마이징",
        "헤어",
        "의상",
        "오드아이",
        "꾸미기",
        "외형",
        "커스텀",
        "스킨",
    ),
}


def normalize_for_category_match(text: str) -> str:
    """Normalize review text for simple substring matching."""
    return normalize_text(text).lower().replace(" ", "")


def extract_category_tags(text: str) -> list[str]:
    """Return every matched category tag for a review."""
    normalized = normalize_for_category_match(text)
    tags: list[str] = []

    for category, patterns in CATEGORY_PATTERNS.items():
        if any(pattern.lower().replace(" ", "") in normalized for pattern in patterns):
            tags.append(category)

    return tags
